site_name: Static Website Template
site_description: Documentation for the template static website.
nav:
  - Home: index.md
  - Architecture Decision Records:
      - testiing: testiing.md
plugins:
  - techdocs-core
